owner: MSBSOUND
repo: status

sites:
  - name: MAGIC STRAWBERRY SOUND
    url: https://www.msbsound.com/
  - name: Reddit r/MSBSOUND
    url: https://www.reddit.com/r/MSBSOUND/
    
status-website:
  cname: status.msbsound.cord.town
  logoUrl: https://gallery.cord.town/media/original/msbsound/logo_text.png
  name: Status | MSBSOUND
  introTitle: "**Upptime** for MSBSOUND"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://msbsound.cord.town/discord
